fake_album_names = ["Galactic Serenity", "Neon Dreamscape", "Whispers of Wonderland", "Midnight Mirage",
                    "Quantum Groove", "Celestial Euphoria", "Enigmatic Echoes", "Ethereal Odyssey", "Radiant Reverie",
                    "Velvet Stardust", "Serendipitous Symphonies", "Luminous Lullabies"]
fake_song_names = [
    "Midnight Serenade",
    "Echoes of Eternity",
    "Whispers in the Wind",
    "Stardust Melodies",
    "Dreamscape Reverie",
    "Celestial Harmony",
    "Sapphire Horizon",
    "Lullaby for Luna",
    "Enchanted Echo",
    "Melancholy Moonlight",
    "Journey to Infinity",
    "Radiant Reminiscence",
    "Serendipity Sonata",
    "Chasing Aurora",
    "Cosmic Crescendo",
    "Serenity in Silence",
    "Aurora Dreams",
    "Velvet Twilight",
    "Ephemeral Elegy",
    "Soulful Stardance",
    "Whimsical Whispers",
    "Twilight Tapestry",
    "Ocean of Dreams",
    "Gossamer Galaxy",
    "Crimson Cosmos",
    "Luminous Lullabies",
    "Spectral Symphony",
    "Nebula Nocturne",
    "Cerulean Cascade",
    "Whirlwind Waltz",
    "Solstice Sonata",
    "Emerald Embrace",
    "Echoes of Eden",
    "Moonlit Mirage",
    "Stellar Serenity",
    "Waves of Wonder",
    "Eternal Euphony",
    "Ethereal Embers",
    "Lost in Luminescence",
    "Sapphire Sinfonia",
    "Vivid Vortex",
    "Lunar Lullaby",
    "Vortex Voyage",
    "Velvet Voyage",
    "Surreal Serenade",
    "Dance of the Dusk",
    "Whispers of Willow",
    "Twilight Tranquility",
    "Crimson Cascade",
    "Sylvan Serenade",
    "Mystic Moonlight",
    "Starlight Serenity",
    "Labyrinth of Lullabies",
    "Lunar Lyric",
    "Crimson Canopy",
    "Waves of Whimsy",
    "Nebula Nectar",
    "Lustrous Lullabies",
    "Cerulean Canopy",
    "Vivid Voyage",
    "Lost in Luminescence",
    "Voyage to Valhalla",
    "Dance of Destiny",
    "Celestial Cantata",
    "Aurora Allegro",
    "Ethereal Ensemble",
    "Lunar Labyrinth",
    "Whispers of Willow",
    "Sonic Solitude",
    "Crimson Cadence",
    "Astral Aria",
    "Enchanted Ensemble",
    "Melodic Mirage",
    "Celestial Cadence",
    "Lustrous Lullaby",
    "Stellar Serenade",
    "Whimsical Waltz",
    "Sylvan Serenity",
    "Celestial Cascade",
    "Velvet Vortex",
    "Sonic Solstice",
    "Aurora Allegro",
    "Cosmic Crescendo",
    "Lunar Lyric",
    "Stellar Solitude",
    "Waves of Whimsy",
    "Astral Allegro",
    "Ephemeral Elegy",
    "Surreal Sonata",
    "Solstice Samba",
    "Twilight Tango",
    "Vivid Vortex",
    "Waves of Wonder",
    "Celestial Canticle",
    "Melodic Mirage",
    "Whirlwind Waltz",
    "Sonic Solitude",
    "Twilight Tango",
    "Stellar Solace",
    "Lustrous Lullabies",
    "Whispers of Willow",
    "Ethereal Embrace",
    "Crimson Cascade",
    "Lunar Lyric",
    "Cerulean Canopy",
    "Whimsical Whispers",
    "Aurora Adagio",
    "Stellar Solitude",
    "Eternal Euphony",
    "Whispers of Willow",
    "Cosmic Crescendo",
    "Lunar Lullaby",
    "Surreal Sonata",
    "Celestial Cascade",
    "Ephemeral Elegy",
    "Nebula Nocturne",
    "Voyage to Valhalla",
    "Astral Allegro",
    "Whirlwind Waltz",
    "Velvet Voyage",
    "Aurora Allegro",
    "Enchanted Ensemble",
    "Lustrous Lullaby",
    "Crimson Cadence",
    "Celestial Cantata",
    "Aurora Adagio",
    "Ethereal Ensemble",
    "Celestial Cascade",
    "Lunar Labyrinth",
    "Sonic Solstice",
    "Sylvan Serenade",
    "Dance of Destiny",
    "Lustrous Lullaby",
    "Astral Allegro",
    "Enchanted Ensemble",
    "Melodic Mirage",
    "Celestial Cadence",
    "Eternal Euphony",
    "Lustrous Lullabies",
    "Stellar Serenade",
    "Whimsical Waltz",
    "Sylvan Serenity",
    "Celestial Cascade",
    "Velvet Vortex",
    "Sonic Solstice",
    "Aurora Allegro",
    "Cosmic Crescendo",
    "Lunar Lyric",
    "Stellar Solitude",
    "Waves of Whimsy",
    "Astral Allegro",
    "Ephemeral Elegy",
    "Surreal Sonata",
    "Solstice Samba",
    "Twilight Tango",
    "Vivid Vortex",
    "Waves of Wonder",
    "Celestial Canticle",
    "Melodic Mirage",
    "Whirlwind Waltz",
    "Sonic Solitude",
    "Twilight Tango",
    "Stellar Solace",
    "Lustrous Lullabies",
    "Whispers of Willow",
    "Ethereal Embrace",
    "Crimson Cascade",
    "Lunar Lyric",
    "Cerulean Canopy",
    "Whimsical Whispers",
    "Aurora Adagio",
    "Stellar Solitude",
    "Eternal Euphony",
    "Whispers of Willow",
    "Cosmic Crescendo",
    "Lunar Lullaby",
    "Surreal Sonata",
    "Celestial Cascade",
    "Ephemeral Elegy",
    "Nebula Nocturne",
    "Voyage to Valhalla",
    "Astral Allegro",
    "Whirlwind Waltz",
    "Velvet Voyage",
    "Aurora Allegro",
    "Enchanted Ensemble",
    "Lustrous Lullaby",
    "Crimson Cadence",
    "Celestial Cantata",
    "Aurora Adagio",
    "Ethereal Ensemble",
    "Celestial Cascade",
    "Lunar Labyrinth",
    "Sonic Solstice",
    "Sylvan Serenade",
    "Dance of Destiny",
    "Lustrous Lullaby",
    "Astral Allegro",
    "Enchanted Ensemble",
    "Melodic Mirage",
    "Celestial Cadence",
    "Eternal Euphony",
    "Lustrous Lullabies",
    "Stellar Serenade",
    "Whimsical Waltz",
    "Sylvan Serenity",
    "Celestial Cascade",
    "Velvet Vortex",
    "Sonic Solstice",
    "Aurora Allegro",
    "Cosmic Crescendo",
    "Lunar Lyric",
    "Stellar Solitude",
    "Waves of Whimsy",
    "Astral Allegro",
    "Ephemeral Elegy",
    "Surreal Sonata",
    "Solstice Samba",
    "Twilight Tango",
    "Vivid Vortex",
    "Waves of Wonder",
    "Celestial Canticle",
    "Melodic Mirage",
    "Whirlwind Waltz",
    "Sonic Solitude",
    "Twilight Tango",
    "Stellar Solace",
    "Lustrous Lullabies",
    "Whispers of Willow",
    "Ethereal Embrace",
    "Crimson Cascade",
    "Lunar Lyric",
    "Cerulean Canopy",
    "Whimsical Whispers",
    "Aurora Adagio",
    "Stellar Solitude",
    "Eternal Euphony",
    "Whispers of Willow",
    "Cosmic Crescendo",
    "Lunar Lullaby",
    "Surreal Sonata",
    "Celestial Cascade",
    "Ephemeral Elegy",
    "Nebula Nocturne",
    "Voyage to Valhalla",
    "Astral Allegro",
    "Whirlwind Waltz",
    "Velvet Voyage",
    "Aurora Allegro",
    "Enchanted Ensemble",
    "Lustrous Lullaby",
    "Crimson Cadence",
    "Celestial Cantata",
    "Aurora Adagio",
    "Ethereal Ensemble",
    "Celestial Cascade",
    "Lunar Labyrinth",
    "Sonic Solstice",
    "Sylvan Serenade",
    "Dance of Destiny",
    "Lustrous Lullaby",
    "Astral Allegro",
    "Enchanted Ensemble",
    "Melodic Mirage",
    "Celestial Cadence",
    "Eternal Euphony",
    "Lustrous Lullabies",
    "Stellar Serenade",
    "Whimsical Waltz",
    "Sylvan Serenity",
    "Celestial Cascade",
    "Velvet Vortex",
    "Sonic Solstice",
    "Aurora Allegro",
    "Cosmic Crescendo"]

fake_comments = [
    "Fantastic melody and rhythm!",
    "The lyrics are so meaningful.",
    "This song gives me chills every time.",
    "Great vocals, such a talented singer.",
    "Perfect blend of instruments.",
    "Can't stop listening to it!",
    "Brings back memories.",
    "Unique and refreshing sound.",
    "Powerful and emotional lyrics.",
    "Catchy chorus, love it!",
    "Incredible production quality.",
    "This song is my new anthem!",
    "The instrumental section is amazing.",
    "Beautiful composition.",
    "I can relate to the lyrics so much.",
    "Awesome beat, makes me want to dance.",
    "Well done on the harmonies.",
    "The energy in this song is contagious.",
    "Impressive vocal range.",
    "Great storytelling through the music.",
    "A masterpiece!",
    "Such a feel-good song.",
    "The arrangement is top-notch.",
    "Can't get enough of this track!",
    "This shit is fucking terrible",
    "My favorite part of this song was when it ended"
    "This song goes crazy on mute",
    "I wish I could go back to a time before I ever heard this garbage",
    "This saved my cousin's life. I was listening to this and he woke up out of a 10 year coma just to turn it off"
]

fake_playlist_titles = [
    "Eclectic Vibes",
    "Soothing Melodies",
    "Urban Beats",
    "Chillwave Jams",
    "Alternative Grooves",
    "Epic Instrumentals",
    "Indie Discovery",
    "Feel Good Anthems",
    "Sunset Serenade",
    "Midnight Rhythms",
    "Acoustic Bliss",
    "Electronic Odyssey",
    "Lush Landscapes",
    "Dreamy Escapes",
    "Vintage Vinyl",
    "Soulful Expressions",
    "Tranquil Resonance",
    "Hyped Up Hits",
    "Mellow Moments",
    "Global Fusion",
    "Rock Classics Rewind",
    "Ambient Echoes",
    "Jazz Fusion Journey",
    "Pop Paradise",
    "Retro Rewind",
    "Cinematic Soundscapes",
    "Latin Groove Fiesta",
    "R&B Rendezvous",
    "Classical Masterpieces",
    "Indie Pop Gems",
    "Dancefloor Delights",
    "Country Crossroads",
    "Ethereal Exploration",
    "Hip Hop Highlights",
    "Reggae Roots",
    "Folk Festival",
    "Bluesy Breakdown",
    "Piano Passion",
    "Funky Fresh",
    "Smooth Jazz Escape",
    "EDM Extravaganza",
    "Vocal Harmony Haven",
    "High Energy Hype",
    "Guitar Greats",
    "Sensual Slow Jams",
    "Futuristic Flow",
    "Old School Hip Hop",
    "Trippy Tunes",
    "Serene Synthesis",
    "Salsa Celebration",
    "Saxophone Serenity",
    "Unplugged Unwind",
    "Laid-back Lounge",
    "Jungle Beats",
    "Sonic Dreamscape",
    "Psychedelic Playground",
    "Lofi Love",
    "Bass Boosted Bangers",
    "Global Groove",
    "Alternative Alcove",
    "Chamber Choir Classics",
    "Electro Swing Soiree",
    "Opera Overdrive",
    "Retro Rock Revival",
    "Trance Treasures",
    "Jazzed Up Jams",
    "Soulful Showcase",
    "Electronic Enlightenment",
    "Bollywood Beats",
    "Vocal Virtuoso",
    "Vibrant Vibe",
    "Grunge Garage",
    "Country Carnival",
    "Ambient Adventure",
    "Blissful Ballads",
    "Latin Lounge",
    "Modern Motown",
    "Smooth Sailing Sounds",
    "Folk Fusion",
    "Bluesy Backtrack",
    "Piano Prelude",
    "Funky Freedom",
    "Jazz Jam Junction",
    "Retro Remix",
    "Cinematic Symphony",
    "Latin Love Affair",
    "R&B Radiance",
    "Classical Crescendo",
    "Indie Inception",
    "Dance Anthem Arena",
    "Country Comfort",
    "Ethereal Elevation",
    "Hip Hop Hootenanny",
    "Reggae Revival",
    "Folk Fandango",
    "Bluesy Blues",
    "Piano Pizzazz",
    "Funky Fiesta",
    "Smooth Jazz Sanctuary",
    "EDM Escape",
    "Vocal Voyage",
    "High Voltage Hits",
    "Guitar Glory",
    "Sensual Serenade",
    "Futuristic Funk",
    "Oldies Goldies",
    "Trippy Tracks",
    "Serendipity Soundtrack",
    "Lofi Lounge",
    "Bassline Bliss",
    "Global Gaze",
    "Alternative Asylum"
]